name: ci
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install curl on Linux
        if:  matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Tests
        run: ./gradlew check -i
